---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - include_role:
        name: ilmt_scanner
        tasks_from: print_playbooks_version

- name: "Uninstall ILMT scanners"
  hosts: all
  strategy: free
  gather_facts: true
  gather_subset: "!all,!min"
  tasks:
    - name: "Uninstall ILMT scanners from WINDOWS endpoints"
      become: true
      become_user: system
      become_method: runas
      block:
        - include_role:
            name: ilmt_scanner
            tasks_from: uninstall_scanner_windows
          vars:
            remove_computer_from_server: true
      when: ansible_facts['os_family'] == 'Windows'

    - name: "Uninstall ILMT scanners from UNIX/Linux endpoints"
      become: true
      block:
        - include_role:
            name: ilmt_scanner
            tasks_from: uninstall_scanner_unix
          vars:
            remove_computer_from_server: true
      when: ansible_facts['os_family'] != 'Windows'

    - name: "Decommission computer from ILMT server"
      block:
        - include_role:
            name: ilmt_scanner
            tasks_from: decommisson_computer
      when: endpoint_id_for_delete is defined and lmt_server_token is defined
