---
- name: "Get scanner facts on Windows endpoints"
  include_role:
    name: ilmt_scanner
    tasks_from: get_scanner_facts_windows

- name: "Check if successful_setup.info file exists on Windows endpoints"
  win_stat:
    path: "{{ lmt_scanner_path_windows }}\\config\\successful_setup.info"
  register: successful_setup_info_win

- name: "Set successful setup info variable on Windows endpoints"
  set_fact:
    successful_setup_info: "{{ 'Successful' if successful_setup_info_win.stat.exists else \
      ('Not available' if hostvars[inventory_hostname]['scanner_version'] == '0.0' else \
      ('Failed' if hostvars[inventory_hostname]['scanner_version'] is version('9.2.22.0', '>=') else 'Unknown'  )) }}"
