---
- name: "Get scanner facts on UNIX/Linux endpoints"
  include_role:
    name: ilmt_scanner
    tasks_from: get_scanner_facts_unix

- name: "Check if successful_setup.info file exists on UNIX/Linux endpoints"
  stat:
    path: "{{ lmt_scanner_path_unix }}/config/successful_setup.info"
  register: successful_setup_info_unix

- name: "Set successful setup info variable on UNIX/Linux endpoints"
  set_fact:
    successful_setup_info: "{{ 'Successful' if successful_setup_info_unix.stat.exists else \
      ('Not available' if hostvars[inventory_hostname]['scanner_version'] == '0.0' else \
      ('Failed' if hostvars[inventory_hostname]['scanner_version'] is version('9.2.22.0', '>=') else 'Unknown'  )) }}"
