---
- name: "Verify scanner installation on Windows endpoints"
  include_role:
    name: ilmt_scanner
    tasks_from: verify_scanner_installation

- name: "Read endpoint id value on Windows endpoints"
  win_command: "cmd.exe /c type \"{{ lmt_scanner_path_windows }}\\config\\endpoint_id.txt\" "
  register: windows_endpoint_id

- name: "Run collect troubleshooting data script on Windows endpoints"
  win_command: collect_support_data.bat
  args:
    chdir: "{{ lmt_scanner_path_windows }}"

- name: Get files in folder support_data
  ansible.windows.win_find:
    paths: "{{ lmt_scanner_path_windows }}\\support_data"
  register: found_support_data

- name: Get latest troubleshooting data file
  set_fact:
    latest_support_file: "{{ (found_support_data.files | sort(attribute='lastwritetime') | last).path }}"

- name: "Remove troubleshooting data archive from Windows endpoints"
  win_file:
    state: absent
    path: "{{ lmt_scanner_path_windows }}\\work\\{{ ansible_host }}_{{ windows_endpoint_id.stdout_lines[0] }}.zip"

- name: "Save useful ansible_facts to ansible_facts.txt file on Windows endpoints"
  win_copy:
    content: "{\n
              ansible_facts['hostname']: {{ ansible_facts['hostname'] | default('') | to_nice_json }}\n
              ansible_facts['domain']: {{ ansible_facts['domain'] | default('') | to_nice_json }}\n
              ansible_facts['fqdn']: {{ ansible_facts['fqdn'] | default('') | to_nice_json }}\n
              ansible_facts['ip_addresses']: {{ ansible_facts['ip_addresses'] | default('') | to_nice_json }}\n
              ansible_facts['user_id'] {{ ansible_facts['user_id'] | default('') | to_nice_json }}\n
              ansible_facts['user_dir']: {{ ansible_facts['user_dir'] | default('') | to_nice_json }}\n
              ansible_facts['architecture']: {{ ansible_facts['architecture'] | default('') | to_nice_json }}\n
              ansible_facts['system']: {{ ansible_facts['system'] | default('') | to_nice_json }}\n
              ansible_facts['os_family']: {{ ansible_facts['os_family'] | default('') | to_nice_json }}\n
              ansible_facts['distribution']: {{ ansible_facts['distribution'] | default('') | to_nice_json }}\n
              ansible_facts['distribution_major_version']: {{ ansible_facts['distribution_major_version'] | default('') | to_nice_json }}\n
              ansible_facts['distribution_version']: {{ ansible_facts['distribution_version'] | default('') | to_nice_json }}\n
              ansible_facts['machine_id']: {{ ansible_facts['machine_id'] | default('') | to_nice_json }}\n
              ansible_facts['powershell_version']: {{ ansible_facts['powershell_version'] | default('') | to_nice_json }}\n
              ansible_facts['windows_domain_member']: {{ ansible_facts['windows_domain_member'] | default('') | to_nice_json }}\n
              ansible_facts['domain']: {{ ansible_facts['domain'] | default('') | to_nice_json }}\n
              ansible_facts['env']: {{ ansible_facts['env'] | default('') | to_nice_json }}\n
              }\n"
    dest: "{{ lmt_scanner_path_windows }}\\work\\ansible_facts.txt"
    force: true

- name: "Create troubleshooting data archive on Windows endpoints"
  win_command: "cmd.exe /c \"\"{{ lmt_scanner_path_windows }}\\bin\\zip.exe\" -S -X -r \
    \"{{ lmt_scanner_path_windows }}\\work\\{{ ansible_host }}_{{ windows_endpoint_id.stdout_lines[0] }}.zip\" \
    \"{{ lmt_scanner_path_windows }}\\work\\ansible_facts.txt\" \
    \"{{ latest_support_file }}\"\" "
  args:
    chdir: "{{ lmt_scanner_path_windows }}"
  register: archive

- name: "Remove troubleshooting data collected by script from Windows endpoints"
  win_file:
    state: absent
    path: "{{ latest_support_file }}"
  when: archive is succeeded

- name: "Fetch troubleshooting data archive from Windows endpoints"
  fetch:
    src: "{{ lmt_scanner_path_windows }}\\work\\{{ ansible_host }}_{{ windows_endpoint_id.stdout_lines[0] }}.zip"
    dest: "{{ lmt_local_file_storage_path }}/{{ lmt_troubleshooting_data_folder }}/"
    flat: true
  register: fetched_files

- name: "Remove troubleshooting data archive from Windows endpoints"
  win_file:
    state: absent
    path: "{{ lmt_scanner_path_windows }}\\work\\{{ ansible_host }}_{{ windows_endpoint_id.stdout_lines[0] }}.zip"
    register: file_name
  when: fetched_files is succeeded
