---
- name: "Create {{ lmt_local_file_storage_path }}/{{ lmt_troubleshooting_data_folder }} for storing \
          troubleshooting data from endpoints on Control Node."
  file:
    path: "{{ lmt_local_file_storage_path }}/{{ lmt_troubleshooting_data_folder }}"
    state: directory
    mode: '0755'
  any_errors_fatal: true
