---
- name: "Check if endpoint_id file exists on IBM i endpoints"
  stat:
    path: "{{ lmt_scanner_path_ibmi }}/config/endpoint_id.txt"
  register: ilmt_scanner_installed_ibmi

- name: "Read endpoint id value on IBM i endpoints"
  shell: "cat \"{{ lmt_scanner_path_ibmi }}/config/endpoint_id.txt\" "
  register: ibmi_endpoint_id
  when: ilmt_scanner_installed_ibmi.stat.exists

- name: "Find isotag file on IBM i endpoints"
  find:
    paths: "{{ lmt_scanner_path_ibmi }}/iso-swid/"
    use_regex: true
    patterns: ['^ibm.com_IBM_License_Metric_Tool-.+\.swidtag$']
  register: scanner_swidtag_names

- name: "Set scanner version variable on IBM i endpoints"
  set_fact:
    scanner_version: "{{ (scanner_swidtag_names.files[0].path | regex_replace('.*ibm.com_IBM_License_Metric_Tool-(.+).swidtag$', '\\1')) \
      if ((scanner_swidtag_names is defined) and (scanner_swidtag_names.files is defined) and \
         (scanner_swidtag_names.files|length > 0)) \
      else '0.0' }}"
    endpoint_id: "{{ ibmi_endpoint_id.stdout if ilmt_scanner_installed_ibmi.stat.exists else 'Not available' }}"
    scanner_installation_path: "{{ lmt_scanner_path_ibmi }}"
