- name: "Run scanner setup script block on IBM i endpoints"
  block:
    - name: "Run scanner setup script on IBM i endpoints"
      command: "qsh setup_all.sh"
      args:
        chdir: "{{ lmt_scanner_path_ibmi }}"
      async: "{{ lmt_scanner_setup_timeout }}"
      poll: 5

- name: "Initiate initial software scan block on IBM i endpoints"
  block:
    - name: "Initiate initial software scan on IBM i endpoints"
      command: "qsh run_sw_and_pack.sh"
      args:
        chdir: "{{ lmt_scanner_path_ibmi }}"
      async: 518400  # 6 days
      poll: 0

- name: "Check if endpoint_id.txt file exists on IBM i endpoints"
  stat:
    path: "{{ lmt_scanner_path_ibmi }}/config/endpoint_id.txt"
  register: ilmt_install_fail_msg
  failed_when: not ilmt_install_fail_msg.stat.exists
