---
- name: "Fail when ILMT Scanner is not installed on UNIX/Linux endpoints"
  stat:
    path: "{{ lmt_scanner_path_unix }}/config/endpoint_id.txt"
  register: ilmt_scanner_installed_unix
  failed_when: not ilmt_scanner_installed_unix.stat.exists
  when: ansible_facts['os_family'] != 'Windows'

- name: "Fail when ILMT Scanner is not installed on WINDOWS endpoints"
  win_stat:
    path: "{{ lmt_scanner_path_windows }}\\config\\endpoint_id.txt"
  register: ilmt_scanner_installed_win
  failed_when: not ilmt_scanner_installed_win.stat.exists
  when: ansible_facts['os_family'] == 'Windows'